---

 - name: installing and launching filebeat
   hosts: webservers
   become: yes
   tasks:

    - name: download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat$

    - name: install filebeat deb
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: drop in filebeat.yml
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: enable and configure system module
      command: /usr/bin/filebeat modules enable system

    - name: setup filebeat
      command: /usr/bin/filebeat setup

    - name: state filebeat service
      command: service filebeat start
